[workspace]
members = [
  "./common",
  "./device",
  "./download",
  "./driver",
  "./enumeration",
  "./sdk",
  "./streaming",
  "./sys",
]
resolver = "3"

[profile.release]
debug = true
lto = true
